name: Autonomus
on:
  issues:
    types:
      - labeled

jobs:
  build:
    if: github.event.label.name == 'autonomus'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: View issue information
      run: |
        echo "Issue title: ${{ github.event.issue.title }}"
    - name: Get and Set Host Url
      run: |
        HOST=$(cut -d " " -f2 <<< $TITTLE)
        echo "HOST=${HOST}" >> $GITHUB_ENV
        echo "set host to ${HOST}"
      env:
          TITTLE: ${{ github.event.issue.title }}
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8 #install the python needed
    - name: Install dependencies and set permission
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.25.1
        chmod +x $GITHUB_WORKSPACE/dev/scripts/yusub
    - name: extract subdomain
      run: |
        ./dev/scripts/yusub $HOST >> $HOST
    - name: get ip from subdomain list
      run: | 
        echo $HOST | python scan.py
        cat "host-${HOST}"